### ISSUE TITLE
Error importing r2r-offer-utils in trias-extractor

### ISSUE THREAD

**Issue by marioscrock** [Ride2Rail/r2r-offer-utils#1]
I receive an error (importerror "No Module named Setuptools") trying to import r2r-offer-utils in trias-extractor using `-e git+https://github.com/Ride2Rail/r2r-offer-utils.git#egg=r2r_offer_utils` in the requirements file. It happens both locally and in the Docker image.

Searching for the error I found this [issue](https://stackoverflow.com/a/65787633/7185047) pointing out that the problem may be related to the `.toml` file.

@lubos31262 @bioticek @CristianCantoro does it work for you? If yes, maybe is related to the structure of the code in the project and I'll try to refactor it.

**Comment by lubos31262** [comment]
Dear Mario,

 I do everything in PyCharm. When using r2r-offer-utils from price-fc as a dependency everything seems working fine.


Now I tried also to clone r2r-offer-utils locally and indeed I experienced similar error:

"ERROR: Command errored out with exit status 1:
     command: /home/lubos/PycharmProjects/r2r-offer-utils/venv/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/lubos/PycharmProjects/r2r-offer-utils/setup.py'"'"'; __file__='"'"'/home/lubos/PycharmProjects/r2r-offer-utils/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/lubos/PycharmProjects/r2r-offer-utils/
    Complete output (3 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'"|

BW,

Lubos.
________________________________
From: Mario Scrocca ***@***.***>
Sent: Tuesday, April 13, 2021 11:01 AM
To: Ride2Rail/r2r-offer-utils ***@***.***>
Cc: lubos31262 ***@***.***>; Mention ***@***.***>
Subject: [Ride2Rail/r2r-offer-utils] Error importing r2r-offer-utils in trias-extractor (#1)


I receive an error (importerror "No Module named Setuptools") trying to import r2r-offer-utils in trias-extractor using -e git+https://github.com/Ride2Rail/r2r-offer-utils.git#egg=r2r_offer_utils in the requirements file. It happens both locally and in the Docker image.

Searching for the error I found this issue<https://stackoverflow.com/a/65787633/7185047> pointing out that the problem may be related to the .toml file.

@lubos31262<https://github.com/lubos31262> @bioticek<https://github.com/bioticek> @CristianCantoro<https://github.com/CristianCantoro> does it work for you? If yes, maybe is related to the structure of the code in the project and I'll try to refactor it.

**Comment by CristianCantoro** [comment]
Solved by 64c4e713c829a7f1380b502d703eceac508994ea.
